### ISSUE TITLE
Conflict of time measurement between paper and code

### ISSUE THREAD

**Issue by lv2020** [zzzzid/IDCA#1]
Thanks for your release of the source code! 

However, it looks like there is a conflict of measurement description between the paper and the source code. In the paper, the acceleration performance is calculated by the execution time of the program. But in the source code, the time is the sum of compiling time, running time, and deleting time as shown in lines 64-74 of https://github.com/zzzzid/IDCA/blob/main/algorithm/CFSCA.py. 

Is it a conflict or just because in your definition, the execution time includes compiling time?

**Comment by zzmmxxx** [comment]
Thank you for your question. 

In this work, we consider the "execution time" as the time to complete the whole compilation and execution, because it is possible that some optimizations, although they reduce the program execution time, may take too long to compile. And some programs need to be compiled and executed repeatedly, we take the compilation time into account, but the speedup obtained by this way may be a little bit lower than the speedup ratio obtained by using the program's execution time. 
If you're interested you can add the code for getting the time to 
'''
command3 = ". /a.out /data/zmx/cBenchdata/automotive_susan_data/1.pgm output_large.smoothing.pgm -s"
execute_terminal_command(command3)
'''
, and don't need change other parts. 
Also, unfortunately, this one doesn't outperforms SRTuner, and we'll follow up on the compiler auto-tuning.

**Comment by lv2020** [comment]
Thanks for the quick response!
